### PR TITLE
As a developer, I want to configure series properties like markers (CHARTS-182)

### PR DESCRIPTION
**Pull request by alvarezguille**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/charts-component/25)

### CODE REVIEW

**Comment by ripla** [comment]
Reviewed 98 of 98 files at r1.
Review status: 95 of 98 files reviewed at latest revision, 36 unresolved discussions, all commit checks successful.

---

<sup>**[configuration-reader.html, line 17 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0YSvyOREsIlOikarS)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/configuration-reader.html#L17)):</sup>
I guess this comment is out of place?

---

<sup>**[demo/area/basic-area.html, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0iODrRwfFGPgg8WRA)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/area/basic-area.html#L11)):</sup>
Renamed element inside format

---

<sup>**[demo/area/percentage-area.html, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0jLIcsG3eLjVlTszH)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/area/percentage-area.html#L12)):</sup>
Rename inside format

---

<sup>**[demo/area/stacked-area.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0jUoIgLpgQaEb6B95)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/area/stacked-area.html#L13)):</sup>
Rename inside format

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 25 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0j_qrLzsCUFAmqVFh)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/column_and_bar/bar-with-negative-stack.html#L25)):</sup>
Rename inside format

---

<sup>**[demo/column_and_bar/basic-column.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0k8EQtrjC7SCFsAe2)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/column_and_bar/basic-column.html#L13)):</sup>
Rename inside format

---

<sup>**[demo/column_and_bar/stacked-percentage-column.html, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0oIPXcXKpP6A419iC)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/column_and_bar/stacked-percentage-column.html#L11)):</sup>
Rename inside format

---

<sup>**[demo/combination/dual-charts.html, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0oXaN2q9hT_xpe_12)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/combination/dual-charts.html#L1)):</sup>
Renamed div

---

<sup>**[demo/combination/dual-charts.html, line 27 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0ob5pllaWOi_R80bO)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/combination/dual-charts.html#L27)):</sup>
Renamed div

---

<sup>**[demo/combination/scatter-and-polygon.html, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0p1SCUnXZTPDxPt8I)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/combination/scatter-and-polygon.html#L14)):</sup>
Rename inside format

---

<sup>**[demo/data/html-table-data-inlined.html, line 48 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0pM37VaXw-KFzfnUE)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/data/html-table-data-inlined.html#L48)):</sup>
Rename inside format

---

<sup>**[demo/data/html-table-data.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0pQ3QiN-Yw34GaQnW)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/data/html-table-data.html#L13)):</sup>
Rename inside format

---

<sup>**[demo/dynamic/master-detail-chart.html, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0py4lUqd11AhNZric)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/dynamic/master-detail-chart.html#L1)):</sup>
Renamed div

---

<sup>**[demo/dynamic/master-detail-chart.html, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0peEpCovFdrec7GXl)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/dynamic/master-detail-chart.html#L12)):</sup>
Rename inside format

---

<sup>**[demo/dynamic/master-detail-chart.html, line 62 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0pnUglziA9v2blry9)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/dynamic/master-detail-chart.html#L62)):</sup>
Rename inside string

---

<sup>**[demo/line_and_scatter/logarithmic-axis.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0r6t2ASC8IrPyYaIP)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/line_and_scatter/logarithmic-axis.html#L6)):</sup>
Rename inside format

---

<sup>**[demo/line_and_scatter/spline-updating-each-second.html, line 27 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0sAcS8abB5XjP87_T)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/line_and_scatter/spline-updating-each-second.html#L27)):</sup>
Rename inside format

---

<sup>**[demo/other/box-plot.html, line 19 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0svdkUuhzPpZ-sdL9)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/box-plot.html#L19)):</sup>
Rename inside format

---

<sup>**[demo/other/error-bar.html, line 26 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0te8qPS52MQ15bcAy)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/error-bar.html#L26)):</sup>
Rename inside format

---

<sup>**[demo/other/error-bar.html, line 33 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0tgXOmBUp39SZVRfo)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/error-bar.html#L33)):</sup>
Rename inside format

---

<sup>**[demo/other/exporting.html, line 27 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0tnbiUQM02ASwycWl)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/exporting.html#L27)):</sup>
Rename inside format

---

<sup>**[demo/other/exporting.html, line 31 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0towMhGHznmslZezZ)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/exporting.html#L31)):</sup>
Rename inside format

---

<sup>**[demo/other/gauge-with-dual-axes.html, line 20 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0tyB3sReHGJZoZwls)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/gauge-with-dual-axes.html#L20)):</sup>
Rename inside format

---

<sup>**[demo/other/waterfall.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0uZWNHS7kGaY8UTay)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/waterfall.html#L6)):</sup>
Rename inside format

---

<sup>**[demo/pie/pie-with-credits.html, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0v2ob_XL4HSb5J8xV)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-credits.html#L3)):</sup>
Rename inside format

---

<sup>**[demo/pie/pie-with-credits.html, line 9 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0v5reX4_FtQ52P4av)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-credits.html#L9)):</sup>
Rename inside format

---

<sup>**[demo/pie/pie-with-gradient-fill.html, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vEeDv5cKyL9L4Nw1)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-gradient-fill.html#L3)):</sup>
Rename inside format

---

<sup>**[demo/pie/pie-with-legend.html, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vJmmdr9ruuhNUwN-)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-legend.html#L3)):</sup>
Rename inside format

---

<sup>**[demo/pie/pie-with-start-and-end-angle.html, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vN66G2qUunsfJRFG)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-start-and-end-angle.html#L3)):</sup>
Rename inside format

---

<sup>**[demo/pie/pie-with-start-and-end-angle.html, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vOU2pZJ8DVV9MRuj)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-start-and-end-angle.html#L7)):</sup>
Rename inside format

---

<sup>**[demo/pie/pie.html, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vTh19sz3KJexDbqM)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie.html#L7)):</sup>
Rename inside format

---

<sup>**[test/chart-fill-color.html, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0ve9qSacEr6nvuq0b)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/chart-fill-color.html#L10)):</sup>
Renamed body

---

<sup>**[test/data-test.html, line 55 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vwkpgkmY_4jO5fUE)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/data-test.html#L55)):</sup>
Renamed table

---

<sup>**[test/data-test.html, line 251 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vzePcwgjvvUc9_uj)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/data-test.html#L251)):</sup>
Renamed table

---

<sup>**[test/pie-config-test.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0we-O5tDkZpczuQwy)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/pie-config-test.html#L13)):</sup>
Rename inside format

---

<sup>**[test/pie-config-test.html, line 17 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0wg58dCKM5GXg9Gou)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/pie-config-test.html#L17)):</sup>
Rename inside format

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/25)

**Comment by ripla** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 33 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/25)

**Comment by alvarezguille** [comment]
Review status: 72 of 100 files reviewed at latest revision, 33 unresolved discussions, all commit checks successful.

---

<sup>**[configuration-reader.html, line 17 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0YSvyOREsIlOikarS)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/configuration-reader.html#L17)):</sup>
Done.

---

<sup>**[demo/area/basic-area.html, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0iODrRwfFGPgg8WRA)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/area/basic-area.html#L11)):</sup>
Done.

---

<sup>**[demo/area/percentage-area.html, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0jLIcsG3eLjVlTszH)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/area/percentage-area.html#L12)):</sup>
Done.

---

<sup>**[demo/area/stacked-area.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0jUoIgLpgQaEb6B95)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/area/stacked-area.html#L13)):</sup>
Done.

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 25 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0j_qrLzsCUFAmqVFh)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/column_and_bar/bar-with-negative-stack.html#L25)):</sup>
Done.

---

<sup>**[demo/column_and_bar/basic-column.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0k8EQtrjC7SCFsAe2)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/column_and_bar/basic-column.html#L13)):</sup>
Done.

---

<sup>**[demo/column_and_bar/stacked-percentage-column.html, line 11 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0oIPXcXKpP6A419iC)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/column_and_bar/stacked-percentage-column.html#L11)):</sup>
Done.

---

<sup>**[demo/combination/dual-charts.html, line 1 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0oXaN2q9hT_xpe_12)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/combination/dual-charts.html#L1)):</sup>
Done.

---

<sup>**[demo/combination/dual-charts.html, line 27 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0ob5pllaWOi_R80bO)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/combination/dual-charts.html#L27)):</sup>
Done.

---

<sup>**[demo/combination/scatter-and-polygon.html, line 14 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0p1SCUnXZTPDxPt8I)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/combination/scatter-and-polygon.html#L14)):</sup>
Done.

---

<sup>**[demo/data/html-table-data-inlined.html, line 48 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0pM37VaXw-KFzfnUE)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/data/html-table-data-inlined.html#L48)):</sup>
Done.

---

<sup>**[demo/data/html-table-data.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0pQ3QiN-Yw34GaQnW)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/data/html-table-data.html#L13)):</sup>
Done.

---

<sup>**[demo/line_and_scatter/logarithmic-axis.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0r6t2ASC8IrPyYaIP)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/line_and_scatter/logarithmic-axis.html#L6)):</sup>
Done.

---

<sup>**[demo/line_and_scatter/spline-updating-each-second.html, line 27 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0sAcS8abB5XjP87_T)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/line_and_scatter/spline-updating-each-second.html#L27)):</sup>
Done.

---

<sup>**[demo/other/box-plot.html, line 19 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0svdkUuhzPpZ-sdL9)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/box-plot.html#L19)):</sup>
Done.

---

<sup>**[demo/other/error-bar.html, line 26 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0te8qPS52MQ15bcAy)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/error-bar.html#L26)):</sup>
Done.

---

<sup>**[demo/other/error-bar.html, line 33 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0tgXOmBUp39SZVRfo)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/error-bar.html#L33)):</sup>
Done.

---

<sup>**[demo/other/exporting.html, line 27 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0tnbiUQM02ASwycWl)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/exporting.html#L27)):</sup>
Done.

---

<sup>**[demo/other/exporting.html, line 31 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0towMhGHznmslZezZ)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/exporting.html#L31)):</sup>
Done.

---

<sup>**[demo/other/gauge-with-dual-axes.html, line 20 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0tyB3sReHGJZoZwls)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/gauge-with-dual-axes.html#L20)):</sup>
Done.

---

<sup>**[demo/other/waterfall.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0uZWNHS7kGaY8UTay)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/other/waterfall.html#L6)):</sup>
Done.

---

<sup>**[demo/pie/pie-with-credits.html, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0v2ob_XL4HSb5J8xV)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-credits.html#L3)):</sup>
Done.

---

<sup>**[demo/pie/pie-with-credits.html, line 9 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0v5reX4_FtQ52P4av)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-credits.html#L9)):</sup>
Done.

---

<sup>**[demo/pie/pie-with-gradient-fill.html, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vEeDv5cKyL9L4Nw1)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-gradient-fill.html#L3)):</sup>
Done.

---

<sup>**[demo/pie/pie-with-legend.html, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vJmmdr9ruuhNUwN-)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-legend.html#L3)):</sup>
Done.

---

<sup>**[demo/pie/pie-with-start-and-end-angle.html, line 3 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vN66G2qUunsfJRFG)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-start-and-end-angle.html#L3)):</sup>
Done.

---

<sup>**[demo/pie/pie-with-start-and-end-angle.html, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vOU2pZJ8DVV9MRuj)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie-with-start-and-end-angle.html#L7)):</sup>
Done.

---

<sup>**[demo/pie/pie.html, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vTh19sz3KJexDbqM)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/demo/pie/pie.html#L7)):</sup>
Done.

---

<sup>**[test/chart-fill-color.html, line 10 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0ve9qSacEr6nvuq0b)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/chart-fill-color.html#L10)):</sup>
Done.

---

<sup>**[test/data-test.html, line 55 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vwkpgkmY_4jO5fUE)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/data-test.html#L55)):</sup>
Done.

---

<sup>**[test/data-test.html, line 251 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0vzePcwgjvvUc9_uj)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/data-test.html#L251)):</sup>
Done.

---

<sup>**[test/pie-config-test.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0we-O5tDkZpczuQwy)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/pie-config-test.html#L13)):</sup>
Done.

---

<sup>**[test/pie-config-test.html, line 17 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/25#-Jw0wg58dCKM5GXg9Gou)** ([raw file](https://github.com/vaadin/charts-component/blob/c8b3c77ff849e05098658619656658b3deb72e8c/test/pie-config-test.html#L17)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/25)

**Comment by ripla** [comment]
Reviewed 28 of 28 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/25)

**Pull request merged**
