### PR TITLE
Add support for JSON list series (CHARTS-142)

### PR DESCRIPTION
**Pull request by alvarezguille**
Series data is now set inside data element
Series can be set with attributes or light-DOM elements

[Review on Reviewable](https://reviewable.io/reviews/vaadin/charts-component/8)

### CODE REVIEW

**Comment by ripla** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[v-series.html, line 126 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/8#-JsZCMneanXLKknFOii3)** ([raw file](https://github.com/vaadin/charts-component/blob/19372a87df55f0e8e2f639f3a4f1bcc96ed3143e/v-series.html#L126)):</sup>
Remove commented out code

---

<sup>**[v-series.html, line 138 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/8#-JsZCXOvVFNr5mm5Beh5)** ([raw file](https://github.com/vaadin/charts-component/blob/19372a87df55f0e8e2f639f3a4f1bcc96ed3143e/v-series.html#L138)):</sup>
And short developer comment on what is done and why it is done

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/8)

**Comment by ripla** [comment]
Seems that the demo is broken for some reason. Test:
    gulp stage
    cd target/zip
    serve
And access [http://localhost:3000/demo.html](http://localhost:3000/demo.html)

This works with _master_.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/8)

**Comment by alvarezguille** [comment]
Review status: 10 of 17 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[v-series.html, line 126 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/8#-JsZCMneanXLKknFOii3)** ([raw file](https://github.com/vaadin/charts-component/blob/19372a87df55f0e8e2f639f3a4f1bcc96ed3143e/v-series.html#L126)):</sup>
Done.

---

<sup>**[v-series.html, line 140 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/8#-JsZCXOvVFNr5mm5Beh5)** ([raw file](https://github.com/vaadin/charts-component/blob/19372a87df55f0e8e2f639f3a4f1bcc96ed3143e/v-series.html#L140)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/8)

**Comment by alvarezguille** [comment]
gulp stage
    cd target/zip
    serve
works now

---

Review status: 10 of 17 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/8)

**Comment by ripla** [comment]
Reviewed 5 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[docs/0.1.0/index.md, line 30 \[r4\]](https://reviewable.io:443/reviews/vaadin/charts-component/8#-Js_W-IUXXnf0bd0qkbO)** ([raw file](https://github.com/vaadin/charts-component/blob/204a3bf4052439d530fd1161b0db410cf4431e57/docs/0.1.0/index.md#L30)):</sup>
I guess we can remove the &quot; ?

---

<sup>**[docs/0.1.0/v-chart.md, line 123 \[r4\]](https://reviewable.io:443/reviews/vaadin/charts-component/8#-Js_WSig2_-qtbnlMa52)** ([raw file](https://github.com/vaadin/charts-component/blob/204a3bf4052439d530fd1161b0db410cf4431e57/docs/0.1.0/v-chart.md#L123)):</sup>
I guess we can remove the &quot; ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/8)

**Comment by alvarezguille** [comment]
Reviewed 1 of 6 files at r2.
Review status: 15 of 17 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[docs/0.1.0/index.md, line 30 \[r4\]](https://reviewable.io:443/reviews/vaadin/charts-component/8#-Js_W-IUXXnf0bd0qkbO)** ([raw file](https://github.com/vaadin/charts-component/blob/204a3bf4052439d530fd1161b0db410cf4431e57/docs/0.1.0/index.md#L30)):</sup>
Done.

---

<sup>**[docs/0.1.0/v-chart.md, line 123 \[r4\]](https://reviewable.io:443/reviews/vaadin/charts-component/8#-Js_WSig2_-qtbnlMa52)** ([raw file](https://github.com/vaadin/charts-component/blob/204a3bf4052439d530fd1161b0db410cf4431e57/docs/0.1.0/v-chart.md#L123)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/8)

**Comment by ripla** [comment]
Reviewed 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/8)

**Pull request merged**
