### PR TITLE
Remove vc prefix from attributes (CHARTS-220)

### PR DESCRIPTION
**Pull request by alvarezguille**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/charts-component/39)

### CODE REVIEW

**Comment by ripla** [comment]
_task_/CHARTS-220, no problem

---

Reviewed 101 of 101 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[configuration-reader.html, line 72 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3EnBLxIBVVR__lKVu)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/configuration-reader.html#L72)):</sup>
Attributes are nodes as well... maybe isElement?

---

<sup>**[configuration-reader.html, line 174 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3E4L3yrJlUmOZYO2o)** ([raw file](https://github.com/vaadin/charts-component/blob/1b48c6f6e6a1cf406d318b7e4cfebbb6cd48ff4e/configuration-reader.html#L174)):</sup>
isVaadinChartsAttribute only applies to elements, right? Maybe it should be renamed?

---

<sup>**[demo/area/area-spline.html, line 19 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3H0DKh6lXGLm68YX9)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/area-spline.html#L19)):</sup>
or fill-opacity?

---

<sup>**[demo/area/inverted-axes.html, line 16 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3HrkGz9OLFZpCo0bo)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/inverted-axes.html#L16)):</sup>
-> fill-opacity

---

<sup>**[demo/area/percentage-area.html, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3IjeXRdsY3Lz52Lv_)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/percentage-area.html#L12)):</sup>
point-format

---

<sup>**[demo/area/stacked-area.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3ItQmlIaNAzpeHjau)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/stacked-area.html#L13)):</sup>
point-format

---

<sup>**[demo/line_and_scatter/basic-line-events.html, line 42 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3YjhiOF1W5h6A2A89)** ([raw file](https://github.com/vaadin/charts-component/blob/1b48c6f6e6a1cf406d318b7e4cfebbb6cd48ff4e/demo/line_and_scatter/basic-line-events.html#L42)):</sup>
Should be a JSON object?

---

<sup>**[demo/other/treemap-with-levels.html, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3e0Nx1UZ4e_0-jw2O)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/other/treemap-with-levels.html#L7)):</sup>
fornt -> font

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/39)

**Comment by ripla** [comment]
_task_/CHARTS-220, no problem

---

Reviewed 101 of 101 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

<sup>**[configuration-reader.html, line 72 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3EnBLxIBVVR__lKVu)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/configuration-reader.html#L72)):</sup>
Attributes are nodes as well... maybe isElement?

---

<sup>**[configuration-reader.html, line 174 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3E4L3yrJlUmOZYO2o)** ([raw file](https://github.com/vaadin/charts-component/blob/1b48c6f6e6a1cf406d318b7e4cfebbb6cd48ff4e/configuration-reader.html#L174)):</sup>
isVaadinChartsAttribute only applies to elements, right? Maybe it should be renamed?

---

<sup>**[demo/area/area-spline.html, line 19 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3H0DKh6lXGLm68YX9)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/area-spline.html#L19)):</sup>
or fill-opacity?

---

<sup>**[demo/area/inverted-axes.html, line 16 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3HrkGz9OLFZpCo0bo)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/inverted-axes.html#L16)):</sup>
-> fill-opacity

---

<sup>**[demo/area/percentage-area.html, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3IjeXRdsY3Lz52Lv_)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/percentage-area.html#L12)):</sup>
point-format

---

<sup>**[demo/area/stacked-area.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3ItQmlIaNAzpeHjau)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/stacked-area.html#L13)):</sup>
point-format

---

<sup>**[demo/line_and_scatter/basic-line-events.html, line 42 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3YjhiOF1W5h6A2A89)** ([raw file](https://github.com/vaadin/charts-component/blob/1b48c6f6e6a1cf406d318b7e4cfebbb6cd48ff4e/demo/line_and_scatter/basic-line-events.html#L42)):</sup>
Should be a JSON object?

---

<sup>**[demo/other/treemap-with-levels.html, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3e0Nx1UZ4e_0-jw2O)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/other/treemap-with-levels.html#L7)):</sup>
fornt -> font

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/39)

**Comment by alvarezguille** [comment]
Review status: 94 of 101 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

<sup>**[configuration-reader.html, line 72 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3EnBLxIBVVR__lKVu)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/configuration-reader.html#L72)):</sup>
Done.

---

<sup>**[configuration-reader.html, line 174 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3E4L3yrJlUmOZYO2o)** ([raw file](https://github.com/vaadin/charts-component/blob/1b48c6f6e6a1cf406d318b7e4cfebbb6cd48ff4e/configuration-reader.html#L174)):</sup>
Changed to _isVaadinChartsProperty

---

<sup>**[demo/area/area-spline.html, line 19 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3H0DKh6lXGLm68YX9)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/area-spline.html#L19)):</sup>
Done.

---

<sup>**[demo/area/inverted-axes.html, line 16 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3HrkGz9OLFZpCo0bo)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/inverted-axes.html#L16)):</sup>
Done.

---

<sup>**[demo/area/percentage-area.html, line 12 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3IjeXRdsY3Lz52Lv_)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/percentage-area.html#L12)):</sup>
Done.

---

<sup>**[demo/area/stacked-area.html, line 13 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3ItQmlIaNAzpeHjau)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/area/stacked-area.html#L13)):</sup>
Done.

---

<sup>**[demo/line_and_scatter/basic-line-events.html, line 42 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3YjhiOF1W5h6A2A89)** ([raw file](https://github.com/vaadin/charts-component/blob/1b48c6f6e6a1cf406d318b7e4cfebbb6cd48ff4e/demo/line_and_scatter/basic-line-events.html#L42)):</sup>
it should be defined with elements, done

---

<sup>**[demo/other/treemap-with-levels.html, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/39#-Jy3e0Nx1UZ4e_0-jw2O)** ([raw file](https://github.com/vaadin/charts-component/blob/c4f6201c07bfb7982d93235ec0ef809fc88fe029/demo/other/treemap-with-levels.html#L7)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/39)

**Comment by ripla** [comment]
Reviewed 7 of 7 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/39)

**Pull request merged**
