### PR TITLE
Add dynamic demos (CHARTS-175)

### PR DESCRIPTION
**Pull request by alvarezguille**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/charts-component/22)

### CODE REVIEW

**Comment by ripla** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[demo/dynamic/master-detail-chart.html, line 95 \[r2\]](https://reviewable.io:443/reviews/vaadin/charts-component/22#-JvU4haAuCvf3oSUFgtZ)** ([raw file](https://github.com/vaadin/charts-component/blob/be9e744016ba096fcd9a74594ccfdd1ec6a9c925/demo/dynamic/master-detail-chart.html#L95)):</sup>
Extra ':'

---

<sup>**[demo/dynamic/xy-chart-selection.html, line 26 \[r2\]](https://reviewable.io:443/reviews/vaadin/charts-component/22#-JvU5BsxOvj2Kd7N1KmG)** ([raw file](https://github.com/vaadin/charts-component/blob/be9e744016ba096fcd9a74594ccfdd1ec6a9c925/demo/dynamic/xy-chart-selection.html#L26)):</sup>
Empty point on purpose?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/22)

**Comment by alvarezguille** [comment]
<sup>**[demo/dynamic/xy-chart-selection.html, line 26 \[r2\]](https://reviewable.io:443/reviews/vaadin/charts-component/22#-JvU5BsxOvj2Kd7N1KmG)** ([raw file](https://github.com/vaadin/charts-component/blob/be9e744016ba096fcd9a74594ccfdd1ec6a9c925/demo/dynamic/xy-chart-selection.html#L26)):</sup>
no

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/22)

**Comment by alvarezguille** [comment]
Review status: 4 of 9 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[demo/dynamic/master-detail-chart.html, line 95 \[r2\]](https://reviewable.io:443/reviews/vaadin/charts-component/22#-JvU4haAuCvf3oSUFgtZ)** ([raw file](https://github.com/vaadin/charts-component/blob/be9e744016ba096fcd9a74594ccfdd1ec6a9c925/demo/dynamic/master-detail-chart.html#L95)):</sup>
property and plotband not needed there actualy

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/22)

**Comment by ripla** [comment]
Reviewed 5 of 5 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/22)

**Pull request merged**
