### PR TITLE
Implement Column and Bar demos (CHARTS-171)

### PR DESCRIPTION
**Pull request by alvarezguille**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/charts-component/15)

### CODE REVIEW

**Comment by ripla** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 5 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-JukA73NxrN3fY5rpOVK)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/bar-with-negative-stack.html#L5)):</sup>
Is it also possible to define the categories inside a categories element?

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-Juk7sn2NwV05PADO12V)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/bar-with-negative-stack.html#L6)):</sup>
Is this default needed?

---

<sup>**[demo/column_and_bar/stacked-percentage-column.html, line 9 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-JukAyKRuOrlnQ8AtAmh)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/stacked-percentage-column.html#L9)):</sup>
Would the point format look nicer as a child element?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/15)

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 5 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-JukA73NxrN3fY5rpOVK)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/bar-with-negative-stack.html#L5)):</sup>
categories is an array attribute, right now inner elements only allow defining json objects
I agree we should consider it, but right now it won't work

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-Juk7sn2NwV05PADO12V)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/bar-with-negative-stack.html#L6)):</sup>
1 is not default, it's a value set to prevent the auto calculation done to prevent overlapping 

---

<sup>**[demo/column_and_bar/stacked-percentage-column.html, line 9 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-JukAyKRuOrlnQ8AtAmh)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/stacked-percentage-column.html#L9)):</sup>
point format is an array attribute, right now inner elements only allow defining json objects
I agree that something needs to be designed for these long att values

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/15)

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-Juk7sn2NwV05PADO12V)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/bar-with-negative-stack.html#L6)):</sup>
in this case all categories should be shown always

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/15)

**Comment by ripla** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-Juk7sn2NwV05PADO12V)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/bar-with-negative-stack.html#L6)):</sup>
Sorry, I meant the reversed attribute

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/15)

**Comment by ripla** [comment]
<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-Juk7sn2NwV05PADO12V)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/bar-with-negative-stack.html#L6)):</sup>
This seems to be a bug in Highcharts.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/15)

**Comment by alvarezguille** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/15#-Juk7sn2NwV05PADO12V)** ([raw file](https://github.com/vaadin/charts-component/blob/a0dcb2ddb224095e0f0ae906d933da6cf2124ae9/demo/column_and_bar/bar-with-negative-stack.html#L6)):</sup>
bar chart is inverted by default, and inverted chart reverses the axes, that's why it's needed to be re-set

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/15)

**Pull request merged**
