### PR TITLE
Feature/charts 177 Add 'other' demos

### PR DESCRIPTION
**Pull request by alvarezguille**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/charts-component/21)

### CODE REVIEW

**Comment by ripla** [comment]
Some suggestions to clean up the history
 * f62a705 and d62d458 are already in master, so they should be removed
 * 8039f0e, 57bfa84 and b006deb could be merged 
 * 1e82120 fix typo, al -> all

---

Review status: 0 of 34 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/21)

**Comment by ripla** [comment]
Reviewed 23 of 24 files at r1, 5 of 15 files at r2, 8 of 9 files at r3, 16 of 16 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 17 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNkHRJAkVIkS1ixN4e)** ([raw file](https://github.com/vaadin/charts-component/blob/49190f80372a4f8d6776375b99bf0832a86d35ae/demo/column_and_bar/bar-with-negative-stack.html#L17)):</sup>
Was this a workaround for something?

---

<sup>**[demo/other/funnel.html, line 2 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNoYeheP_EICGiYLX9)** ([raw file](https://github.com/vaadin/charts-component/blob/acf4389218c521596901bc034803279f482845ea/demo/other/funnel.html#L2)):</sup>
Extra space

---

<sup>**[demo/other/solid-gauge.html, line 2 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNpfJlqwyKeJYo0FnZ)** ([raw file](https://github.com/vaadin/charts-component/blob/acf4389218c521596901bc034803279f482845ea/demo/other/solid-gauge.html#L2)):</sup>
So setting title to `<title></title` doesn't work?

---

<sup>**[demo/other/windrose.html, line 9 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNqAyh9RqSox4zaSHG)** ([raw file](https://github.com/vaadin/charts-component/blob/acf4389218c521596901bc034803279f482845ea/demo/other/windrose.html#L9)):</sup>
Missing end-tag?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/21)

**Comment by alvarezguille** [comment]
Review status: 30 of 35 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 17 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNkHRJAkVIkS1ixN4e)** ([raw file](https://github.com/vaadin/charts-component/blob/49190f80372a4f8d6776375b99bf0832a86d35ae/demo/column_and_bar/bar-with-negative-stack.html#L17)):</sup>
not workaround, it's to override default yaxis title 
"The Y axis title is disabled by setting the text option to null. Defaults to Values."
but should be         
<title text=""></title>
or
<title text="null"></title>

---

<sup>**[demo/other/funnel.html, line 2 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNoYeheP_EICGiYLX9)** ([raw file](https://github.com/vaadin/charts-component/blob/acf4389218c521596901bc034803279f482845ea/demo/other/funnel.html#L2)):</sup>
Done.

---

<sup>**[demo/other/solid-gauge.html, line 2 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNpfJlqwyKeJYo0FnZ)** ([raw file](https://github.com/vaadin/charts-component/blob/acf4389218c521596901bc034803279f482845ea/demo/other/solid-gauge.html#L2)):</sup>
"To disable the title, set the text to null. Defaults to Chart title."
but should be         
<title text=""></title>
or
<title text="null"></title>

---

<sup>**[demo/other/windrose.html, line 9 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNqAyh9RqSox4zaSHG)** ([raw file](https://github.com/vaadin/charts-component/blob/acf4389218c521596901bc034803279f482845ea/demo/other/windrose.html#L9)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/21)

**Comment by ripla** [comment]
Reviewed 1 of 1 files at r5.
Review status: 30 of 35 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/21)

**Comment by alvarezguille** [comment]
<sup>**[demo/other/solid-gauge.html, line 2 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNpfJlqwyKeJYo0FnZ)** ([raw file](https://github.com/vaadin/charts-component/blob/acf4389218c521596901bc034803279f482845ea/demo/other/solid-gauge.html#L2)):</sup>
should be
`<title text=""></title>`
or
`<title text="null"></title>`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/21)

**Comment by alvarezguille** [comment]
<sup>**[demo/column_and_bar/bar-with-negative-stack.html, line 17 \[r5\]](https://reviewable.io:443/reviews/vaadin/charts-component/21#-JvNkHRJAkVIkS1ixN4e)** ([raw file](https://github.com/vaadin/charts-component/blob/49190f80372a4f8d6776375b99bf0832a86d35ae/demo/column_and_bar/bar-with-negative-stack.html#L17)):</sup>
should be
`<title text=""></title>`
or
`<title text="null"></title>`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/21)

**Comment by ripla** [comment]
Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/21)

**Pull request merged**
