### PR TITLE
Add support for data configuration (CHARTS-134)

### PR DESCRIPTION
**Pull request by ripla**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/charts-component/24)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[demo/sourcing-component.html, line 62 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/24#-JvnyYcdWeMZMRDZqOvf)** ([raw file](https://github.com/vaadin/charts-component/blob/329f16d03d9f7174aabb055c9c49c543d8925507/demo/sourcing-component.html#L62)):</sup>
is this finally needed?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/24)

**Comment by ripla** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[demo/sourcing-component.html, line 62 \[r1\]](https://reviewable.io:443/reviews/vaadin/charts-component/24#-JvnyYcdWeMZMRDZqOvf)** ([raw file](https://github.com/vaadin/charts-component/blob/329f16d03d9f7174aabb055c9c49c543d8925507/demo/sourcing-component.html#L62)):</sup>
No, reverted

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/24)

**Comment by alvarezguille** [comment]
can we try to clean a0fe8ac and b291711

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/24)

**Comment by ripla** [comment]
Cleaned.

---

Review status: 1 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/24)

**Comment by alvarezguille** [comment]
Reviewed 2 of 8 files at r1, 4 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/charts-component/24)

**Pull request merged**
